### PR TITLE
VS2017 Upgrade - Adds a few Hooks also

### PR DESCRIPTION
**Pull request by redsand**
VS2017 builds successfully.

Adds a few more minor hooks.

### CODE REVIEW

**Comment by doomedraven** [comment]
Good one, i was fighting with this few weeks ago

**Comment by kevoreilly** [comment]
Thanks for these - I had missed this when I made some changes to the signatures submitted earlier today, so I ended up swapping out the calls for VirtualAlloc as these calls all get picked up by the underlying NtAllocateVirtualMemory hook. 

I think it might be worth sticking with the underlying 'native' API hooks if these catch the relevant calls, although it is debatable.

Similarly if the VirtualProtectFromApp ends up calling NtProtectVirtualMemory then we shouldn't need to hook that function explicitly, although I am open to being persuaded otherwise.

**Comment by redsand** [comment]
Oh... i didn't know they all reduced to NtProtectVirtualMemory.  I wasn't
sure, since one of them had a CUDA reference and thought maybe it was
possible M$ used a different code path.  My fault.

Let me know what you'd like me to do, if anything.

Tim

**Comment by kevoreilly** [comment]
No worries - I wasn't sure myself but I've just checked Win10 KernelBase.dll - VirtualProtectFromApp calls VirtualProtect which calls NtProtectVirtualMemory. So we should have this covered by the NtProtectVirtualMemory hook. I'll try and merge the other changes separately though,

**Comment by kevoreilly** [comment]
Hmm it doesn't appear to be straightforward to only apply the VS 2017 commits. I'm not sure if you can remove commits from the request?

**Comment by redsand** [comment]
I've cleaned up my commit to only represent the VS2017 upgrade + a few
functions for Fls that were in therefrom before, needed for code execution
indirection tracking. Similar tricks are used with Tls (TlsSetValue) let me
know if you'd like me to zap that file and make a separate pull request.

Tim

**Comment by kevoreilly** [comment]
Thanks for that - all sounds good. Let me test this on my existing VS2015 and I need to install 2017 too.

**Comment by kevoreilly** [comment]
@redsand - thanks again for these commits - I have finally moved dev IDE to VS2017 so have merged your changes as three separate commits comprising the contents of this PR:

https://github.com/ctxis/capemon/commit/a2cfb4de9b786a7c6a93a0a943a996b4ecb7f7ce
https://github.com/ctxis/capemon/commit/01748076c3462b2ca4386d46b3c08ebedfe953da
https://github.com/ctxis/capemon/commit/06d36a9a1fd6698fe67b6a7609d9e7b1bbdf4820

**Pull request closed without merging**
